ready for review
DFineev/java-shareit pull request #3
Opened 2023-12-09 22:09 UTC by DFineev

2023-12-10 13:54 UTC, Yang-Pi requested changes
Общий момент: в задании просят реализовать тестирование репозиториев с использованием @DataJpaTest [https://howtodoinjava.com/spring-boot2/testing/datajpatest-annotation/]

2023-12-10 13:54 UTC, Yang-Pi commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +class BookingControllerTest {
Добавь еще пару тестов на негативные сценарии

2023-12-11 14:26 UTC, DFineev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +class BookingControllerTest {
Тесты написал, но с DataJpaTest пока не удалось разобраться. что-то не заводится. 
Т.к. это не было в обязательных замечаниях от тебя и т.к. время поджимает - направил на ревью. 
Параллельно ломаю голову почему не могу обратиться к другим репозиториям в рамках теста bookingRepository

2023-12-11 15:53 UTC, Yang-Pi commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +class BookingControllerTest {
Почему не можешь - я вижу, что UserRepo используется

2023-12-11 15:56 UTC, Yang-Pi requested changes
DataJpaTest все же нужны, они указаны в задании, поэтому хотя бы один, но нужно написать

2023-12-12 21:33 UTC, Yang-Pi approved these changes

2024-01-23 17:19 UTC, merged